config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  
  devise_for :users, :controllers => {registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, only: %i[ index edit show update ] # resources :users, must be after devise_for :users to prevent redirecting loops
  resources :tags, only: %i[create index destroy]
  resources :courses, except: [:edit] do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      # Add two new actions to our routes
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort 
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: %i[ new create ]
    resources :course_wizard, controller: 'courses/course_wizard'
  end
  
  resources :youtube, only: :show
  
  
  get 'home/index'
  get "activity", to: "home#activity"
  get "analytics", to: "home#analytics"
  get "privacy_policy", to: "home#privacy_policy"
  root "home#index"
  
  
  # Charts Routes
  # get "charts/users_per_day", to: "charts#users_per_day"
  # get "charts/enrollments_per_day", to: "charts#enrollments_per_day"
  # get "charts/course_popularity", to: "charts#course_popularity"
  # get "charts/most_paid_courses", to: "charts#most_paid_courses"
  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'most_paid_courses'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :privacy_policy]
  def index
    # using scopes to move the logic to models instead of controllers
    @courses = Course.all.limit(3)
    @latest_courses = Course.latest_courses.published.approved
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews
    
    @popular_courses = Course.popular_courses.published.approved
    @top_rated_courses = Course.top_rated_courses.published.approved
    @purchased_courses = Course.all.limit(3).joins(:enrollments).where(enrollments: {user: current_user}).order(created_at: :desc)
    
    @popular_tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc).limit(10)
    
  end

  def privacy_policy
  end
  
  def activity
    if current_user.has_role?(:admin)
      @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end
  
  def analytics
    if current_user.has_role?(:admin)
      # @users = User.all
      # @courses = Course.all
      # @enrollments = Enrollment.all
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end
  
end

app/views/home/activity.html.haml
- content_for :title do
  Coursemy
  \|
  Activity

%h3
  .text-center
    Activity
    .badge.bg-info
      = @activities.count


- @activities.each do |activity|
  %ul.list-group
    %li.list-group-item 
      = activity.created_at.strftime("%d/%b/%Y - %H:%M") 
      (#{time_ago_in_words(activity.created_at)}) 
      = activity.trackable_type
      // dynamic icon based on model
      = model_label(activity.trackable_type)
      // to solve nested resources activity error
      - if activity.trackable_type == 'Lesson'
        - if Lesson.where(id: activity.trackable_id).present?
          = link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
        - else
          Lesson Was Deleted
      - elsif activity.trackable_type == 'Comment'
        - if Comment.where(id: activity.trackable_id).present?
          = link_to activity.trackable, course_lesson_path(activity.trackable.lesson.course, activity.trackable.lesson)
        - else
          Comment Was Deleted
      - else
        = link_to activity.trackable, activity.trackable
      = activity.key
      // dynamic icon based on crud method
      = crud_label(activity.key.match(/\.(.*)/)[1])
      by
      = link_to activity.owner, user_path(activity.owner)
      - if activity.parameters.any?
        = activity.parameters
      
!= pagy_bootstrap_nav(@pagy)

app/views/home/analytics.html.haml
%h3
  Users created per day
/= line_chart @users.group_by_day(:created_at).count
= line_chart charts_users_per_day_path
%h3
  Enrollments Created per day
/= column_chart @enrollments.group_by_day(:created_at).count
= line_chart charts_enrollments_per_day_path
%h3
  Courses Popularity
// = pie_chart @courses.group(:enrollments_count).count
= bar_chart charts_course_popularity_path

%h3
  Most Paid Courses
// = pie_chart @courses.group(:enrollments_count).count
= bar_chart charts_most_paid_courses_path

app/views/home/index.html.haml
- content_for :title do
  Coursemy
  \|
  Online Courses - Learn On Your Own Pace
  
.container-fluid.purple-background.text-light.p-5
  .container.purple-background.p-5
    .display-4 
      What Do you want to learn today?
    
    .p-4
    
    - if current_user
      .form-inline.my-2.my-lg-0
        = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
          .input-group
            = f.search_field :title_or_short_description_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
            %span.input-group-append
              %button.btn.btn-primary.btn-sm{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}
    - else
      %h3.text-shadow Join to access all the courses
      .p-2
      = link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg'
      = link_to 'Login', new_user_session_path, class: 'btn btn-primary btn-lg'
      .row.mt-1
      = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'btn btn-danger btn-lg mr-1' do
        Continue with
        .fab.fa-google
      .row.mt-1
      = link_to user_github_omniauth_authorize_path, method: :post, class: 'btn btn-info btn-lg mr-1' do
        Continue with
        .fab.fa-github
      .row.mt-1
      = link_to user_facebook_omniauth_authorize_path, method: :post, class: 'btn btn-primary btn-lg mr-1' do
        Continue with
        .fab.fa-facebook
    %p
    
.card-group
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a vaiety of fresh topics
  .card.card-body
    %h1
      .fas.fa-chalkboard-teacher
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    Active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime Access
    .row
    Learn at your own pace

- if current_user
  %hr
  %h4
    .fas.fa-user-graduate
    Continue Learning
  .grid-container
    - @purchased_courses.each do |course|
      = render 'courses/course', course: course
  .text-end
    = link_to "Check All Your Courses", purchased_courses_path
%hr
%h4
  .fas.fa-chart-line
  Popular Courses
.grid-container
  - @popular_courses.each do |course|
    = render 'courses/course', course: course
.text-end
  = link_to "More Popular Courses", courses_path(courses_search: {s: 'enrollments_count desc'})
%hr
%h4
  .fas.fa-star
  Top Rated Courses
.grid-container
  - @top_rated_courses.each do |course|
    = render 'courses/course', course: course
.text-end
  = link_to "Best Rated Courses", courses_path(courses_search: {s: 'average_rating desc'})
%hr
%h4
  .fas.fa-clock
  Latest Courses
.grid-container
  - @latest_courses.each do |course|
    = render 'courses/course', course: course
.text-end
  = link_to "Check All Latest Courses", courses_path(courses_search: {s: 'created_at desc'})
  
%hr
%h4 
  .fas.fa-tags
  Most Popular Tags
- @popular_tags.each do |tag|
  = link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}) do
    .badge.bg-info
      = tag.name
      = tag.course_tags_count
      
%hr
%h4
  .fas.fa-comment
  What are our students saying?
.grid-container
  - @latest_good_reviews.each do |enrollment|
    = render 'enrollments/enrollment', enrollment: enrollment

app/views/home/privacy_policy.html.haml
%h2 Privacy Policy
%p
  Your privacy is important to us. It is Coursemy's policy to respect your privacy regarding any information we may collect from you across our website,
  = succeed "," do
    %a{:href => "http://coursemy.herokuapp.com"} http://coursemy.herokuapp.com
%p We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.
%p We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.
%p We don’t share any personally identifying information publicly or with third-parties, except when required to by law.
%p Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.
%p You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.
%p Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.
%p This policy is effective as of 24 April 2020.