config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  
  devise_for :users, :controllers => {registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, only: %i[ index edit show update ] # resources :users, must be after devise_for :users to prevent redirecting loops
  resources :tags, only: %i[create index destroy]
  resources :courses, except: [:edit] do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      # Add two new actions to our routes
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort 
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: %i[ new create ]
    resources :course_wizard, controller: 'courses/course_wizard'
  end
  
  resources :youtube, only: :show
  
  
  get 'home/index'
  get "activity", to: "home#activity"
  get "analytics", to: "home#analytics"
  get "privacy_policy", to: "home#privacy_policy"
  root "home#index"
  
  
  # Charts Routes
  # get "charts/users_per_day", to: "charts#users_per_day"
  # get "charts/enrollments_per_day", to: "charts#enrollments_per_day"
  # get "charts/course_popularity", to: "charts#course_popularity"
  # get "charts/most_paid_courses", to: "charts#most_paid_courses"
  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'most_paid_courses'
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  #Course.find_each { |course| Course.reset_counters(course.id, :enrollments) }   counter cache for old records
  belongs_to :user, counter_cache: true
  #User.find_each { |user| User.reset_counters(user.id, :enrollments) }  counter cache for old records
  
  validates_presence_of :review, if: :rating?
  validates_presence_of :rating, if: :review?
  
  validates_uniqueness_of :course_id, scope: :user_id  #user cannot subscribe to same course twice
  validates_uniqueness_of :user_id, scope: :course_id  #user cannot subscribe to same course twice
  
  validate :cant_subscribe_to_own_course   # user cannot subscribe to his own courses
  
  scope :pending_review, -> {where(rating: [0, nil, ""], review: [0, nil, ""])}
  scope :reviewed, -> {where.not(review: [0, nil, ""])}
  scope :latest_good_reviews, -> {order(rating: :desc, created_at: :desc).limit(3)}
  
  extend FriendlyId
  friendly_id :to_s, use: :slugged
  
  def to_s
    user.to_s + " " + course.to_s
  end
  
  after_save do
    unless  rating.nil? || rating.zero?
      course.update_rating
    end
  end
  
  after_destroy do 
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end
  
  after_create :calculate_balance
  after_destroy :calculate_balance
  
  def calculate_balance
    course.calculate_income
    user.calculate_enrollment_expenses
  end
  
  protected
  def cant_subscribe_to_own_course
    if self.new_record? #when creating a new enrollment check for the user_id
      if self.user_id.present?
        if user_id == course.user_id
          errors.add(:base, "You can not subscribe to your own course")
        end
      end
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[certificate]  # to allow it available for the user that completed the course to use it anywhere
  before_action :set_enrollment, only: %i[ show edit update destroy certificate]
  before_action :set_course, only: %i[ new create ]
  # GET /enrollments or /enrollments.json
  def index
    @ransack_path = enrollments_path
    @q = Enrollment.ransack(params[:q])
    # @enrollments = @q.result(distinct: true)
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    authorize @enrollments
  end
  
  def my_students
    @ransack_path = my_students_enrollments_path
    @q = Enrollment.joins(:course).where(courses: {user: current_user}).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render 'index'
  end 


  def certificate
    authorize @enrollment, :certificate?
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@enrollment.course.title}, #{@enrollment.user.email}",
        page_size: 'A4',
        template: "enrollments/certificate.pdf.haml"
      end
    end
  end
  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
    authorize @enrollment
  end

  # POST /enrollments or /enrollments.json
  def create
    if @course.price > 0
      # allow paying with stripe
      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )
      charge = Stripe::Charge.create(
        customer:    customer.id,
        amount:      (@course.price * 100).to_i,
        description: @course.title,
        currency:    'usd'
      )
    end
    @enrollment = current_user.buy_course(@course)
    redirect_to course_path(@course), notice: "You Have successfully enrolled in this course"
    # Tell the EnrollmentMailer to send an enrollment email 
    EnrollmentMailer.new_enrollment(@enrollment).deliver_later
    EnrollmentMailer.teacher_enrollment(@enrollment).deliver_later
    
    
    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_course_enrollment_path(@course)
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    authorize @enrollment
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_course
      @course = Course.friendly.find(params[:course_id])
    end 
    
    def set_enrollment
      @enrollment = Enrollment.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:rating, :review)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.haml
// %p#notice= notice

// %p
//   %b Course:
//   = @enrollment.course
// %p
//   %b User:
//   = @enrollment.user
// %p
//   %b Rating:
//   = @enrollment.rating
// %p
//   %b Review:
//   = @enrollment.review
// %p
//   %b Price:
//   = @enrollment.price

// = link_to 'Edit', edit_enrollment_path(@enrollment)
// \|
// = link_to 'Back', enrollments_path
.card
  .card-header
    .fa.fa-user
    = link_to enrollment.user.username, user_path(enrollment.user)
    .fa.fa-clock
    = time_ago_in_words(enrollment.updated_at)
    .fa.fa-graduation-cap
    = link_to enrollment.course, course_path(enrollment.course)
  .card-body
    .text-warning.fa.fa-star
    %b= enrollment.rating
    .fa.fa-comment
    %small= enrollment.review
  - if current_user
    .card-footer
      - if policy(enrollment).edit?
        = link_to "Edit Review", edit_enrollment_path(enrollment)

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    //, as: :radio_buttons
    = f.input :rating, collection: 1..5 
    = f.input :review
  
  %p
  .form-actions
    = f.button :submit

app/views/enrollments/certificate.pdf.haml
%center
  %div{:style => "width:1200px; height:800px; padding:20px; text-align:center; border: 10px solid #563d7c"}
    %div{:style => "width:1150px; height:750px; padding:20px; text-align:center; border: 5px solid #563d7c"}
      %br
      %br
      %span{:style => "font-size:50px; font-weight:bold"} Certificate of Completion
      %br
      %br
      %br
      %br
      %p
      %h2
        This is to certify that the user:
        %br
        %br
        %b
        %u
          = @enrollment.user.email
        %br
        %br
        %b
        has successfully completed the course:
        %br
        %br
        %b
        %u
          = @enrollment.course.title
        %br
        %br
        %b
        on the Coursemy platform
      
      %p
      %br
      %br
      %br
      %b Certificate id: 
      #{@enrollment.slug}
      
      %p
      
      %b Certificate url: 
      #{request.base_url}#{request.original_fullpath}
      %br
      %br
      %br
      %br
      %br
      
      %center
        %h3
          = image_tag wicked_pdf_asset_base64('logo.jpg'), height: "30", width: "auto"
          %p
          www.Coursemy.com 

app/views/enrollments/edit.html.haml
- content_for :title do
  Coursemy
  \|
  Add Review
  = @enrollment.to_s
%p
.card
  .card-header
    %h3
      .text-warning.fas.fa-star
      Add Review
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show Review', @enrollment, class: "btn btn-secondary"
    \|
    = link_to 'Back to course', course_path(@enrollment.course), class: "btn btn-warning"

app/views/enrollments/index.html.haml
- content_for :title do
  Coursemy
  \|
  = action_name.humanize
  
%h3
  .text-center
    = action_name.humanize
    Enrollments
    .badge.bg-info
      = @enrollments.count
      
= search_form_for @q, url: @ransack_path do |f|
  // _cont for strings, _eq for integers, ransack methods
  = f.search_field :user_email_cont, placeholder: 'User'
  = f.search_field :course_title_cont, placeholder: 'Course'
  = f.search_field :price_eq, placeholder: 'Price'
  = f.search_field :review_cont, placeholder: 'Review'
  = f.search_field :rating_eq, placeholder: 'Rating'   
  = f.submit
.ml-2
= link_to 'refresh', @ransack_path

.table-responsive
  %table.table.table-bordered.table-striped.table-sm
    %thead
      %tr
        %th ID
        %th
          .fa.fa-user
          = sort_link(@q, :user_email, "User")
        %th 
          .fa.fa-clock
          .fa.fa-lock-open
          Enrolled At
        %th 
          .fa.fa-graduation-cap
          = sort_link(@q, :course_title, "Course")
        %th
          .fa.fa-dollar-sign
          = sort_link(@q, :price)
        %th
          .text-warning.fa.fa-clock
          = sort_link(@q, :updated_at, "Reviewed at")
        %th
          .text-warning.fa.fa-star
          = sort_link(@q, :rating)
        %th 
          .text-warning.fa.fa-comment
          Review
        %th
          Progress
        %th
          Certificate
        %th
        %th
  
    %tbody
      - @enrollments.each do |enrollment|
        %tr
          %td= enrollment.id
          %td= link_to enrollment.user, user_path(enrollment.user)
          %td= enrollment.created_at.strftime("%d/%b/%Y - %H:%m")
          %td= link_to enrollment.course, course_path(enrollment.course) 
          %td= number_to_currency(enrollment.price)
          %td
            - if enrollment.rating.present?
              = enrollment.updated_at.strftime("%d/%b/%Y - %H:%m")
          %td= enrollment.rating
          %td= enrollment.review
          %td= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0)
          %td= link_to 'Certificate', certificate_enrollment_path(enrollment, format: :pdf)
          %td= link_to 'See Review', enrollment
          %td
            - if policy(enrollment).edit?
              = link_to 'Add Review', edit_enrollment_path(enrollment)
          %td
            - if policy(enrollment).destroy?
              = link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }
  
  %br
  != pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 
  /= link_to 'New Enrollment', new_enrollment_path

app/views/enrollments/new.html.haml
- content_for :title do
  Coursemy
  \|
  New enrollment
  
.card
  .card-header
    %h3
      .fas.fa-graduation-cap
      = link_to @course.title, course_path(@course)
      %hr
      .fas.fa-lock-open
      Buy Course:
      = number_to_currency(@course.price)
  .card-body
    - if @course.price > 0
      = form_tag course_enrollments_path(@course) do
        // = submit_tag "Pay #{number_to_currency(@course.price)}", class: "btn btn-lg btn-success"
        %script.stripe-button{"data-amount" => "#{(@course.price * 100).to_i}",
                              "data-description" => "#{@course.title} (#{number_to_currency @course.price})",
                              "data-email" => "#{current_user.email}",
                              "data-key" => "pk_test_51JYqTnIEBj5WhntAyZY0Nj332KEvXTspTCWpdmAlhrM2LaJVawa2Gw4TKiaX1hrO0DoGUYiqrKWl5oukcTfbVAqD00b7XGohBf",
                              "data-locale" => "auto",
                              :src => "https://checkout.stripe.com/checkout.js"}
                              
    - else
      = form_tag course_enrollments_path(@course) do
        = submit_tag "Enroll For Free", class: "btn btn-lg btn-success"
      
  .card-footer
    = link_to 'Back', course_path(@course), class: "btn btn-warning"

app/views/enrollments/show.html.haml
= render "enrollments/enrollment", enrollment: @enrollment

app/views/enrollments/show.pdf.haml
%center
  %div{:style => "width:1200px; height:800px; padding:20px; text-align:center; border: 10px solid #563d7c"}
    %div{:style => "width:1150px; height:750px; padding:20px; text-align:center; border: 5px solid #563d7c"}
      %br
      %br
      %span{:style => "font-size:50px; font-weight:bold"} Certificate of Completion
      %br
      %br
      %br
      %br
      %p
      %h2
        This is to certify that the user:
        %b
          = @enrollment.user.email
        has successfully completed the course
        %b
          = @enrollment.course.title
        on the Coursemy.com platform
      
      %p
      %br
      %br
      %br
      %b Certificate id: 
      #{@enrollment.slug}
      
      %p
      
      %b Certificate url: 
      #{request.base_url}#{request.original_fullpath}
      %br
      %br
      %br
      %br
      %br
      %br
      %br
      
      %center
        %h3
          = image_tag wicked_pdf_asset_base64('logo.jpg'), height: "30", width: "auto"
          %p
          www.Coursemy.com 