config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  
  devise_for :users, :controllers => {registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, only: %i[ index edit show update ] # resources :users, must be after devise_for :users to prevent redirecting loops
  resources :tags, only: %i[create index destroy]
  resources :courses, except: [:edit] do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      # Add two new actions to our routes
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort 
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: %i[ new create ]
    resources :course_wizard, controller: 'courses/course_wizard'
  end
  
  resources :youtube, only: :show
  
  
  get 'home/index'
  get "activity", to: "home#activity"
  get "analytics", to: "home#analytics"
  get "privacy_policy", to: "home#privacy_policy"
  root "home#index"
  
  
  # Charts Routes
  # get "charts/users_per_day", to: "charts#users_per_day"
  # get "charts/enrollments_per_day", to: "charts#enrollments_per_day"
  # get "charts/course_popularity", to: "charts#course_popularity"
  # get "charts/most_paid_courses", to: "charts#most_paid_courses"
  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'most_paid_courses'
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course, counter_cache: true
  #Course.find_each { |course| Course.reset_counters(course.id, :lessons) } # counter cache for old records
  validates :title, :content, :course, presence: true
  
  validates :title, length: { :maximum => 70}
  
  validates_uniqueness_of :title, scope: :course_id
  # validates :video_thumbnail, presence: true, if: :video_present?
  
  # def video_present?
  #   self.video.present?
  # end
  
  has_many :user_lessons, dependent: :destroy
  has_many :comments, dependent: :nullify
  
  has_one_attached :video
  has_one_attached :video_thumbnail
  validates :video,
    content_type: ['video/mp4'], 
    size: { less_than: 50.megabytes , message: 'size should be under 50 megabytes' }
  validates :video_thumbnail,
    content_type: ['image/png', 'image/jpg', 'image/jpeg'], 
    size: { less_than: 500.kilobytes , message: 'size should be under 500 kilobytes' }
  
  
  has_rich_text :content
  extend FriendlyId
  friendly_id :title, use: :slugged   # use title as slug
  
  include RankedModel
  ranks :row_order, with_same: :course_id
  
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user}
  
  
  def to_s
    title
  end
  
  def prev
    course.lessons.where("row_order < ?", row_order).order(:row_order).last
  end
  
  def next
    course.lessons.where("row_order > ?", row_order).order(:row_order).first
  end
  
  def viewed(user)
    unless user == self.course.user # if user != self.course.user
      self.user_lessons.where(user: user).present?
    # self.user_lessons.where(user_id: user.id, lesson: self.id).present?
    end
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show edit update destroy delete_video]
  
  
  def delete_video
    authorize @lesson, :edit?
    @lesson.video.purge
    @lesson.video_thumbnail.purge
    redirect_to edit_course_lesson_path(@course, @lesson), notice: "Video has successfully deleted"
  end
  
  def sort
    @course = Course.friendly.find(params[:course_id])
    lesson = Lesson.friendly.find(params[:lesson_id])
    authorize lesson, :edit?
    lesson.update(lesson_params)
    render body: nil
  end
  
  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
    authorize @lesson
    current_user.view_lesson(@lesson)
    @lessons = @course.lessons
    @comment = Comment.new
    @comments = @lesson.comments.order(created_at: :desc)
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])
  end

  # GET /lessons/1/edit
  def edit
    authorize @lesson
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.friendly.find(params[:course_id])
    @lesson.course_id = @course.id
    authorize @lesson
    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: "Lesson was successfully created." }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: "Lesson was successfully updated." }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to course_path(@course), notice: "Lesson was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @course = Course.friendly.find(params[:course_id])
      @lesson = Lesson.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :content, :row_order_position, :video, :video_thumbnail) #, :course_id
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([@course, @lesson]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :content, as: :rich_text_area
    %p
    - if @lesson.video.attached?
      = @lesson.video.filename
      - if policy(@lesson).edit?
        = link_to "Remove Video And Thumbnail", delete_video_course_lesson_path(@course, @lesson),
        method: :delete, data: { confirm: "Are you sure you want to delete this video?!"}
    %p
    = f.input :video
    %p
    - if @lesson.video_thumbnail.attached?
      = @lesson.video_thumbnail.filename
    = f.input :video_thumbnail
    // = f.association :course
    //= f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden
  
  %p
  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
  .card-header
    - if lesson.viewed(current_user) == true
      .text-success.fas.fa-check-square
    - else
      .far.fa-square
    = link_to lesson.title, course_lesson_path(@course, lesson)
  - if policy(lesson).show?
    .card-body
      - if @lesson.video.attached?
        - if @lesson.video_thumbnail.attached?
          %video(controls="true" poster="#{url_for @lesson.video_thumbnail}" width="100%" preload="metadata" controlslist="nodownload")
            %source{src: rails_blob_url(@lesson.video), type:"#{@lesson.video.content_type}"}
        - else
          %video(controls="true" width="100%" preload="metadata"  controlslist="nodownload")
            %source{src: rails_blob_url(@lesson.video), type:"#{@lesson.video.content_type}"}
          /VIDEO-JS VIDEO
          /= content_tag :video, id: 'my-video' do
          /  = tag :source, src: url_for(@lesson.video), type: @lesson.video.content_type
      = lesson.content
  - if policy(lesson).edit?
    .card-footer
      = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: "btn text-centerbtn-sm btn-warning"
      = link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger"
  .card-footer
    - unless lesson.prev.nil?
      .float-start
        = link_to course_lesson_path(@course, lesson.prev), class: "btn btn-sm btn-info" do
          Previous Lesson
          .fas.fa-arrow-left
    - unless lesson.next.nil?
      .float-end
        = link_to course_lesson_path(@course, lesson.next), class: "btn btn-sm btn-info" do
          Next Lesson
          .fas.fa-arrow-right 

app/views/lessons/_lesson_preview.html.haml
- if policy(lesson).show?
  - if lesson.viewed(current_user) == true
    .text-success.fas.fa-check-square
  - else
    .far.fa-square
  = link_to course_lesson_path(@course, lesson) do
    = lesson.row_order_rank + 1 
    = lesson.title
    
- else
  = lesson.row_order_rank + 1 
  = lesson.title
     
.float-end
  .fa.fa-comment
  Comments:
  = lesson.comments_count
  - if policy(lesson).edit?
    .fa.fa-eye
    Interactions:
    = lesson.user_lessons.map(&:impressions).sum
    .fa.fa-eye
    Unique Views:
    = lesson.user_lessons_count
    = link_to 'Edit', edit_course_lesson_path(@course, lesson), class: "btn btn-sm btn-warning"
    = link_to 'Destroy', [@course, lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger"

app/views/lessons/edit.html.haml
- content_for :title do
  Coursemy
  \/
  Course
  = @course.title
  \/
  Edit
  = @lesson.title

= link_to 'Courses', courses_path
\/
= link_to @lesson.course.title, course_path(@lesson.course)
\/
= link_to @lesson.title, course_lesson_path(@course, @lesson)
\/ 
Edit
%p
.card
  .card-header
    %h3 
      .far.fa-check-square
      Editing lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show lesson', course_lesson_path(@course, @lesson), class: "btn btn-secondary"
    \|
    = link_to 'Back to course', course_path(@lesson.course), class: "btn btn-warning"

app/views/lessons/new.html.haml
- content_for :title do
  Coursemy
  \/
  Course
  = @course.title
  \/
  New Lesson
= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
%p
.card
  .card-header
    %h3 
      .far.fa-check-square
      New lesson
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back to course', course_path(@course), class: "btn btn-warning"

app/views/lessons/show.html.haml
- content_for :title do
  Coursemy
  \/
  Course
  = @course.title
  \/
  Lesson
  = @lesson.title

= link_to 'Courses', courses_path
\/
= link_to @lesson.course.title, course_path(@lesson.course)
\/
= link_to @lesson.title, course_lesson_path(@course, @lesson)
%p

// = @lesson.user_lessons.where(user: current_user).first.impressions

.row
  .col-lg-8
    = render "lessons/lesson", lesson: @lesson
    .row
    %p
    %h4
      .fas.fa-comment
      Comments:
      = @lesson.comments_count
    %p
    .card
      .card-header
        New Comment
      .card-body
        = render 'lessons/comments/form'
    %p
    .row
    - @comments.each do |comment|
      = render 'lessons/comments/comment', comment: comment
      %p
  .col-lg-4
    %ul.list-group
      %li.list-group-item
        .fas.fa-graduation-cap
        = link_to @lesson.course.title, course_path(@lesson.course) 
        .row
        Progress: 
        .fas.fa-spinner
        = number_to_percentage(@course.progress(current_user), precision: 0)
      - @lessons.each do |lesson|
        - if @lesson.present? && lesson == @lesson
          %li.list-group-item.list-group-item-primary
            = render 'lessons/lesson_preview', lesson: lesson
        - else 
          %li.list-group-item
            = render 'lessons/lesson_preview', lesson: lesson