config/routes.rb
Rails.application.routes.draw do
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  
  devise_for :users, :controllers => {registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, only: %i[ index edit show update ] # resources :users, must be after devise_for :users to prevent redirecting loops
  resources :tags, only: %i[create index destroy]
  resources :courses, except: [:edit] do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do 
      # Add two new actions to our routes
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort 
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: %i[ new create ]
    resources :course_wizard, controller: 'courses/course_wizard'
  end
  
  resources :youtube, only: :show
  
  
  get 'home/index'
  get "activity", to: "home#activity"
  get "analytics", to: "home#analytics"
  get "privacy_policy", to: "home#privacy_policy"
  root "home#index"
  
  
  # Charts Routes
  # get "charts/users_per_day", to: "charts#users_per_day"
  # get "charts/enrollments_per_day", to: "charts#enrollments_per_day"
  # get "charts/course_popularity", to: "charts#course_popularity"
  # get "charts/most_paid_courses", to: "charts#most_paid_courses"
  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'most_paid_courses'
  end
end

app/controllers/courses/course_wizard_controller.rb
class Courses::CourseWizardController < ApplicationController
  include Wicked::Wizard
  before_action :set_progress, only: %i[show update]
  before_action :set_course, only: %i[show update finish_wizard_path]
  

  steps :basic_info, :details, :lessons, :publish
  
  def show
    authorize @course, :edit?
    case step
    when :basic_info
    when :details
      @tags = Tag.all
    when :lessons
    when :publish
    end
    render_wizard
  end
  
  def update
    authorize @course, :edit?
    case step
    when :basic_info
    when :details
      @tags = Tag.all
    when :lessons
    when :publish
    end
    @course.update(course_params)
    # go to next page
    render_wizard @course 
  end
  
  def finish_wizard_path
    authorize @course, :edit?
    course_path(@course)
  end
  
  private
    def set_progress
      if wizard_steps.any? && wizard_steps.index(step).present?
        @progress = ((wizard_steps.index(step) + 1).to_d / wizard_steps.count.to_d) * 100
      else
        @progress = 0
      end
    end
    
    def set_course
      @course = Course.friendly.find(params[:course_id])
    end
    
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :language, :level, :price, :published, :avatar, tag_ids: [], lessons_attributes: [:id, :title, :content, :_destroy])
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show destroy approve unapprove analytics]  #:edit, :update
  skip_before_action :authenticate_user!, only: %i[index show]
  
  # GET /courses or /courses.json
  #ransack_path is used to redirect to each ransck path after finishing the search instead of redirecting to the index path
  def index
    @ransack_path = courses_path
    
    @ransack_courses = Course.published.approved.ransack(params[:courses_search], search_key: :courses_search)
    #@courses = @ransack_courses.result.includes(:user)
    
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag)) # allow searching using tag through course_tags 
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
  end
  
  def purchased 
    @ransack_path = purchased_courses_path
    @ransack_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag)) # allow searching using tag through course_tags 
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end 
  
  def pending_review 
    @ransack_path = pending_review_courses_path
    @ransack_courses = Course.joins(:enrollments).merge(Enrollment.pending_review.where({user: current_user})).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag)) # allow searching using tag through course_tags 
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end 
  
  def created 
    @ransack_path = created_courses_path
    @ransack_courses = Course.where({user: current_user}).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag)) # allow searching using tag through course_tags 
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end 
  
  def unapproved 
    @ransack_path = unapproved_courses_path
    @ransack_courses = Course.unapproved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag)) # allow searching using tag through course_tags 
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end 
  
  def approve
    authorize @course, :approve?
    @course.update_attribute(:approved, true)
    redirect_to @course, notice: "Course is successfully approved and visible."
  end
  
  def unapprove
    authorize @course, :approve?
    @course.update_attribute(:approved, false)
    redirect_to @course, notice: "Course is unapproved and invisible."
  end
  
  def analytics
    authorize @course, :owner?
  end
  
  def show
    authorize @course
    @lessons = @course.lessons.rank(:row_order)
    @enrollments_with_reviews = @course.enrollments.reviewed
  end

  def new
    @course = Course.new
    authorize @course
    @tags = Tag.all
  end

  # Edit only from course wizard
  # def edit
  #   authorize @course
  #   @tags = Tag.all
  # end

  def create
    @course = Course.new(course_params)
    authorize @course
    @course.description = "Curriculum Description"
    @course.short_description = "Short Description"
    @course.user = current_user
    @tags = Tag.all

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_course_wizard_index_path(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        @tags = Tag.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # Update only from course wizard
  # def update
  #   authorize @course
  #   respond_to do |format|
  #     if @course.update(course_params)
  #       format.html { redirect_to @course, notice: "Course was successfully updated." }
  #       format.json { render :show, status: :ok, location: @course }
  #     else
  #       @tags = Tag.all
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @course.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to @course, notice: "Error! This course has enrollments and cannot be destroyed."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :language, :level, :price, :published, :avatar, tag_ids: [])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user
        link_to "You created this course. View Statistics", analytics_course_path(course)
      elsif course.enrollments.where(user_id: current_user).any?
        link_to  course_path(course) do 
          "<i class='fas fa-spinner'></i>".html_safe + " " +      
          number_to_percentage(course.progress(current_user), precision: 0) # precision 0 to remove zeros after the dot 100.000% -> 100%
        end
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: "btn btn-md btn-success"
      else
        link_to "Free", new_course_enrollment_path(course), class: "btn btn-md btn-success" 
      end
    else
      link_to "Check Price", new_course_enrollment_path(course), class: "btn btn-md btn-success"
    end
  end
  
  def review_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if user_course.pending_review.any?
          link_to edit_enrollment_path(user_course.first) do
            "<i class='text-warning fas fa-star'></i>".html_safe + "" +      
            "<i class='text-dark fas fa-question'></i>".html_safe + "" +     
            "Add a review"
          end
        else
          link_to enrollment_path(user_course.first) do 
            "<i class='text-warning fas fa-star'></i>".html_safe + " " +      
            "<i class='text-dark fas fa-check'></i>".html_safe + " " +     
            "Thanks for your review! Check Your Review"
          end
        end
      end
    end
  end
  
  
  def certificate_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if @course.progress(current_user) == 100
          link_to  certificate_enrollment_path(user_course.first, format: :pdf), class: "btn btn-sm btn-danger"  do
            "<i class='far fa-file-pdf'></i>".html_safe + " " +      
            "Certificate of completion"
            
          end
        else
          "Complete the course to view certificate"
        end
      end
    end 
  end
  
  
  
  
  
  
  
end

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  - if course.avatar.attached?
    .card-img-top
      = image_tag course.avatar, height: "200px", width: "100%"
      /= image_tag course.avatar.variant(resize_to_limit: [100, 100])
  .card-body
    %small= simple_format(course.short_description)
  .card-footer
    .text-center
      = enrollment_button(course)
      .row 
      = review_button(course)
  .card-footer
    .row
      .col-md-6
        .text-warning.fas.fa-star
          = course.average_rating
        (  
        .fas.fa-user-graduate
        = course.enrollments_count
        )
        .fas.fa-book
        = course.lessons_count
      .col-md-6
        .fas.fa-chalkboard-teacher
        = link_to course.user.username, user_path(course.user)
  .card-footer
    .row
      .col-md-6
        .fas.fa-globe-europe
        = course.language
      .col-md-6
        .fas.fa-signal
        = course.level 
  .card-footer
    .row
      .col-md-6
        .far.fa-clock
        = course.created_at.strftime('%d-%b-%Y')
  
  - if course.tags.present?
    .card-footer
      - course.tags.each do |tag|
        .badge.bg-info
          = tag.name 
        
  - if current_user
    - if policy(course).owner?
      .card-footer
        %p
        = link_to "Add New Lesson", new_course_lesson_path(course, @lesson), class: "btn btn-sm btn-primary" 
        = link_to course_course_wizard_index_path(course), class: 'btn btn-sm btn-warning'  do
          .fa.fa-edit
          Edit 
        - if policy(course).destroy?
          = link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
        = link_to analytics_course_path(course), class: 'btn btn-sm btn-info' do
          .fa.fa-chart-bar
          Analytics
    - if policy(course).admin_or_owner?
      .card-footer
        -if course.published?
          .badge.bg-success Published
        - else
          .badge.bg-danger UnPublished
        -if course.approved?
          .badge.bg-success Approved
        - else
          .badge.bg-danger UnApproved
    - if policy(course).approve?
      .card-footer
        -if course.approved?
          = link_to "Unapprove", unapprove_course_path(course), method: :patch, class: "btn btn-sm btn-danger"
        - else
          = link_to "Approve", approve_course_path(course), method: :patch, class: "btn btn-sm btn-success"
      

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
  
  %p
  .form-actions
    = f.button :submit

app/views/courses/analytics.html.haml
- content_for :title do
  Coursemy
  \|
  = @course.title 
  \| 
  Analytics
= link_to 'Courses', courses_path
\|
= link_to @course.title, course_path(@course)
\|
Analytics 
.text-center
  %h3
    .fas.fa-chart-line
    Analytics For
    = @course.title
    
%h3
Enrollments Per Day, Quantity
= line_chart @course.enrollments.group_by_day(:created_at).count

Enrollments Per Day, Revenue
= line_chart @course.enrollments.group_by_day(:created_at).sum(:price)

Impressions Per Lesson, (How many nique users lessons have viewed)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').count

Impressions Per Lesson, (How many Times lessons have viewed)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').sum(:impressions)

app/views/courses/edit.html.haml
- content_for :title do
  Coursemy
  \|
  Edit
  = @course.title
= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
%p
.card
  .card-header
    %h3
      .fas.fa-graduation-cap
      Editing course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show', @course, class: "btn btn-secondary"
    \
    = link_to 'Back', courses_path, class: "btn btn-warning"

app/views/courses/index.html.haml
- content_for :title do
  Coursemy
  \|
  = action_name.humanize

%h3
  .text-center
    = action_name.humanize
    courses
    .badge.bg-info
      = @courses.count

.row
  .col-md-2
    = search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f|
      // _cont for strings, _eq for integers, ransack methods
      = f.label :title
      = f.search_field :title_cont, placeholder: 'Title', class: "form-control form-control-sm"
      %p
      = f.label :tag
      // search tag_name through course_tags
      = f.search_field :course_tags_tag_name_cont, placeholder: 'Tag', class: "form-control form-control-sm" 
      %p
      = f.label :short_description
      = f.search_field :short_description_cont, placeholder: 'Short description', class: "form-control form-control-sm"
      %p
      //= f.select :language_cont, ['Arabic', 'English', 'Polish'], include_blank: true, placeholder: 'Language', class: "form-control form-control-sm"
      = f.label :language
      = f.select :language_cont, Course.languages, include_blank: true, placeholder: 'Language', class: "form-control form-control-sm"
      %p
      = f.label :level
      = f.select :level_cont, Course.levels, include_blank: true, placeholder: 'Level', class: "form-control form-control-sm"
      %p
      = f.label :price
      = f.search_field :price_eq, placeholder: 'Price', class: "form-control form-control-sm"
      %p
      = f.label :teacher
      = f.search_field :user_email_cont, placeholder: 'User email', class: "form-control form-control-sm"
      %p
      = sort_link(@ransack_courses, :price)
      .row
      = sort_link(@ransack_courses, :average_rating, "Top Rated")
      .row
      = sort_link(@ransack_courses, :enrollments_count, "Popular")
      .row
      = sort_link(@ransack_courses, :created_at, "Latest")
      
      .row
      = f.submit
    .ml-2
    = link_to 'refresh', @ransack_path
    .row 
      .col-md-2
        - @tags.all.each do |tag|
          // controller: controller_name, action: action_name to return to same controller and action
          = link_to controller: controller_name, action: action_name, courses_search: {course_tags_tag_id_eq: tag.id} do
            .badge.bg-info
              = tag.name
              = tag.course_tags_count
    
  .col-md-10
    .grid-container
      - @courses.each do |course|
        = render 'courses/course', course: course
    %p
    != pagy_bootstrap_nav(@pagy)
    
%br

app/views/courses/new.html.haml
- content_for :title do
  Coursemy
  \|
  New Course

.card
  .card-header
    %h3
      .fas.fa-graduation-cap
      New course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back', courses_path

app/views/courses/show.html.haml
- content_for :title do
  Coursemy
  \|
  = @course.title
= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)
%p

.row
  // for browser resize
  .col-lg-8.order-1.order-lg-1 
    .jumbotron
      %h3
        = @course.title
      .p-3
      .row
      .fas.fa-clock
      = @course.updated_at.strftime("%d/%b/%Y")
      .row
      .fas.fa-globe-europe
      = @course.language
      .fas.fa-signal
      = @course.level
      %hr
      = @course.description
    %h4
      .fas.fa-tasks
      = pluralize(@course.lessons_count, 'Lesson') + " :"
      .float-end
        - unless @course.lessons_count.zero?
          .fas.fa-spinner
          = number_to_percentage(@course.progress(current_user), precision: 0)
          = certificate_button(@course)    
    - if @course.user == current_user
      .list-group.lesson-sortable
        - @lessons.each do |lesson|
          = content_tag "div", id: "lesson-#{lesson.id}", data: { model_name: lesson.class.name.underscore, update_url: course_lesson_sort_path(@course, lesson)} do
            .list-group-item
              .fa.fa-sort.all-scroll{:style => "cursor: grab;"}
              = render 'lessons/lesson_preview', lesson: lesson
    - elsif policy(@course).show?
      .list-group.shadow
        - @lessons.each do |lesson|
          .list-group-item.list-group-item-secondary
            = render 'lessons/lesson_preview', lesson: lesson
    %p
    %h4
      .far.fa-comment 
      = pluralize(@enrollments_with_reviews.count, 'Review')
      /= @course.enrollments_count -> this show all the enrollments even if there is no review so using @enrollments_with_reviews is the right choice
    - @enrollments_with_reviews.each do |enrollment|
      = render 'enrollments/enrollment', enrollment: enrollment
      
  .col-lg-4.order-0.order-lg-1
    .sticky-top
      = render 'courses/course', course: @course
      
%h4
%hr
  Similar Courses
- Course.all.where.not(id: @course.id).each do |course|
  .row
  // Return all courses with the same tag as the current opened course 
  - unless @course.tags.pluck(:id).intersection(course.tags.pluck(:id)).count.zero?
    .grid-container
      = render 'courses/course', course: course
      